series: GLFW Graphics
title: Marching Cubes Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: In this demo we construct a Sphere using marching cubes algorithm.
language: C++
tags:
  - Graphics
extra_resources:
  - title: Adaptive Cube Tessellation for Topologically Correct Isosurfaces
    link: "https://www.jvrb.org/past-issues/5.2008/1309"
  - title: Wikipedia article for Marching cubes
    link: "https://en.wikipedia.org/wiki/Marching_cubes"
  - title: A visual representation of the algorithm
    link: "https://www.youtube.com/watch?v=LfttaAepYJ8"
connections:
  - series: GLFW Graphics
    title: Improved 3D
